### ISSUE TITLE
Malaria cancer therapy - things that makes this hard?

### ISSUE THREAD

**Issue by reinismu** [thethoughtemporium/Whose-gene-is-it-anyway#8]
Hey,

Firstly, I very appreciate your work and that you inspire even more people to learn and pursue hard problems.

I watched whole stream and it seemed just too easy. I understand that I don't have enough knowledge here, but I would really like to know what would make this hard/impossible. I recently got diagnosed with cancer and there are some things that just bug me after watching you stream.

* Is it the immunity that 95% of time just kills of injected virus? And then scientists have to iterate and do slight randomish changes until it works?
* Is there some hard constraints that plasmid must follow for it to work and it is hard computing to get it to work?
* Are trails so long and expensive that most of ideas don't get anywhere?
* Are humans so different from each other that there is just too much risk?
* Are you the first one who come up with idea to use malaria + hiv?
* Why wouldn't multi billion dollar companies just throw money on this and iterate over all possible plasmids that could achieve this? (patents?) Or they have but everything failed. (But then why)

p.s. It seemed funny to me how creating plasmid looked very similar to hacking with ROP ([https://en.wikipedia.org/wiki/Return-oriented_programming](url)) to me.

**Comment by reinismu** [comment]
Well thanks for answering at least one question...

**Comment by billbarni** [comment]
This is just my opinion about your questions:
1 - Depends on what is your way of delivery. Depends on what virus and if it is clearly detectable by your immune system. If you use human-based code, it can help. Many tweaks here and there. 'Randomish'.
2 - There are many constraints, those are defined by several things, from the host to the available code and proteins. Computing is not necessarily of even usefull most of the time here. Some labs do auto-dna encoding and decoding for various stuff, using A.I. and whatnot, this is not that.
3 - Most ideas don't get anywhere because they simply do not work even when you changed a LOT of things and you don't have the resources to really decect why it is not working or resources to find a new gene that will help you. Another great research destruction is done by regulations. Another destroyer is copyrighted DNA.
4 - I don't think he is the first one to use the 'techniques' of this delivery and attack method, no.
5 - You have to iterate once, compile it into real DNA using a lab, put it into a delivery method, deliver it into a sample, test, and than go to the next one. They are doing that and they are getting rich already with immuno therapy using genes they 'own', but it is VERY expensive and only allowed in very few countries.
4
